spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coachem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    database_platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop # update create-only

server:
  port: 8080
  error:
    include-stacktrace: never
