spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coachem?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root

  jpa:
    database_platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: create-drop # update create-only

  mail:
    enabled: true
    host: smtp.gmail.com
    port: 587
    username: 'noreply.coachem@gmail.com'
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  error:
    include-stacktrace: never

