name: Deploy

on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    build:
        name: Build
        
        defaults:
            run:
                working-directory: frontend/coachem
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install Dependencies
              uses: bahmutov/npm-install@v1

            - name: Build project
              run: npm run build

            - name: Upload files for pages
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./build

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  name: production-files
                  path: ./build

            - name: Deploy to github pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
